name: Test Krist

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:15

    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_USER: test_krist
          MYSQL_DATABASE: test_krist
          MYSQL_PASSWORD: test_krist
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn run test
        env: 
          DB_HOST: mariadb
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          TEST_DB_PASS: test_krist
          REDIS_HOST: redis
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          PUBLIC_URL: localhost:8080
